import { createHash } from 'node:crypto';
import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('.',import.meta.url);
await build({entryPoints:[new URL('ui/app.js',root).pathname],outfile:new URL('ui/app.generated.js',root).pathname,bundle:true,format:'esm',target:'es2022',minify:true,external:['/blog_wasm.js']});
await build({entryPoints:[new URL('ui/preview.worker.js',root).pathname],outfile:new URL('ui/preview.worker.generated.js',root).pathname,bundle:true,format:'esm',target:'es2022',minify:true,external:['/blog_wasm.js']});
const paths=[['/','ui/index.html','text/html; charset=utf-8'],['/style.css','ui/style.css','text/css; charset=utf-8'],['/app.js','ui/app.generated.js','text/javascript; charset=utf-8'],['/preview.worker.js','ui/preview.worker.generated.js','text/javascript; charset=utf-8'],['/blog_wasm.js','ui/wasm/blog_wasm.js','text/javascript; charset=utf-8'],['/blog_wasm_bg.wasm','ui/wasm/blog_wasm_bg.wasm','application/wasm']];
const assets={};
for(const [path,file,type] of paths){const bytes=await readFile(new URL(file,root));assets[path]={type,data:bytes.toString('base64'),etag:'\"'+createHash('sha256').update(bytes).digest('hex')+'\"'};}
await writeFile(new URL('src/assets.generated.ts',root),'// Generated by build-ui.mjs. Do not edit.\nexport const ASSETS: Record<string,{type:string;data:string;etag:string}> = '+JSON.stringify(assets)+';\n');
console.log('Bundled editor and Rust preview assets.');
